name: Release

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/helm-install.yml

jobs:
  helm-install:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo 'Hello world'