name: Helm Chart Verify

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/helm-verify.yml

jobs:
  helm-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG key
        run: |
          curl https://github.com/pavlovic-ivan/charts/blob/master/pubkey.asc -o pubkey.asc
          ls -la
          gpg --dearmor --batch --import pubkey.asc
        # run: |
        #   trap "rm -f pubkey.gpg" EXIT
        #   cat > pubkey.gpg << EOF
        #   ${{ secrets.GPG_PUBKEY }}
        #   EOF
        #   gpg --batch --import pubkey.gpg
        #   gpg --export >~/.gnupg/pubring.gpg
      - name: Add Helm repo
        run: helm repo add myrepo https://pavlovic-ivan.github.io/charts 
      - name: Verify helm chart
        run: helm pull --verify myrepo/siembol