name: Release

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/helm-install.yml

jobs:
  helm-install:
    runs-on: ubuntu-latest
    steps:
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Echo
        run: |
          helm repo add dummyrepo https://pavlovic-ivan.github.io/charts
          helm search repo siembol
          helm install siembol dummyrepo/siembol --dry-run