name: Release

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/helm-install.yml

jobs:
  helm-install:
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG key
        run: |
          cat > pubkey.gpg << EOF
          ${{ secrets.GPG_PUBKEY }}
          EOF
          trap "rm -f pubkey.gpg" EXIT
          gpg --batch --import pubkey.gpg
          gpg --list-keys
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Echo
        run: |
          helm repo add dummyrepo https://pavlovic-ivan.github.io/charts
          helm search repo siembol
          helm pull --verify siembol dummyrepo/siembol