name: Helm Chart Verify

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/helm-verify.yml

jobs:
  helm-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG key
        run: |
          curl https://raw.githubusercontent.com/pavlovic-ivan/charts/master/pubkey.asc | gpg --import
          gpg --export >~/.gnupg/pubring.gpg
      - name: Verify helm chart
        run: |
          helm repo add myrepo https://pavlovic-ivan.github.io/charts 
          helm pull --verify myrepo/siembol