name: Release

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/helm-install.yml

jobs:
  helm-install:
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG key
        run: |
          cat > pubring.gpg << EOF
          ${{ secrets.GPG_PUBKEY }}
          EOF
          gpg --batch --import pubring.gpg
          mv pubring.gpg ~/.gnupg
          gpg --list-keys
          ls -la ~/.gnupg
      - name: Echo
        run: |
          helm repo add dummyrepo https://pavlovic-ivan.github.io/charts
          helm search repo siembol
          helm pull --verify dummyrepo/siembol