name: Helm Chart Verify

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/helm-verify.yml

jobs:
  helm-verify:
    uses: pavlovic-ivan/charts/.github/workflows/helm-verify.yml@master
    secrets:
      GPG_PUBKEY: ${{ secrets.GPG_PUBKEY }}
    with:
      CHART: siembol-0.1.10.tgz