name: Release

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/helm-install.yml

jobs:
  helm-install:
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG key
        run: |
          trap "rm -f pubkey.gpg" EXIT
          cat > pubkey.gpg << EOF
          ${{ secrets.GPG_PUBKEY }}
          EOF
          gpg --batch --import pubkey.gpg
          gpg --export >~/.gnupg/pubring.gpg
      - name: Echo
        run: |
          helm repo add dummyrepo https://pavlovic-ivan.github.io/charts
          helm search repo siembol
          helm pull --verify dummyrepo/siembol