name: Release

on:
  push:
    branches:
      - main

jobs:
  invoke-push:
    uses: pavlovic-ivan/charts/.github/workflows/invoke-push.yml@master
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}